'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5477
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _Select() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_Select", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Balon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Balon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Balon_Oficial() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Balon Oficial", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Baloteli() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Baloteli", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Chen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Edgar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edgar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Estadio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Estadio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EstadioNight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EstadioNight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FIFA_2014() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FIFA 2014", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FIFA_TITLE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FIFA TITLE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FifaBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FifaBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FifaBack1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FifaBack1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FifaBack11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FifaBack11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FifaBack2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FifaBack2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fifaback3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fifaback3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fifaback4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fifaback4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fifaback5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fifaback5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fifaback6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fifaback6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FifaBack7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FifaBack7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FIFASong() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("FIFASong", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Gianluigi_Buffon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gianluigi Buffon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Iker_Casillas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Iker Casillas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Inauguracion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Inauguracion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Leave() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Leave", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Llorch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Llorch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mascota() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mascota", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MenuBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Messi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Messi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Move() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Move", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property MusicSymbol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MusicSymbol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Neymar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Neymar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ScoreBoard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScoreBoard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Steve() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Steve", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Super_Smash_Bros__Brawl___Intro__HD_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Super_Smash_Bros__Brawl___Intro__HD_", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property young_cristiano_ronaldo_wallpaper_1408911882() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("young-cristiano-ronaldo-wallpaper-1408911882", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
